### PR TITLE
Set specific item and widget references for passages (WBL-77)

### PR DESCRIPTION
**Pull request by rakeshqdsa**
This is for converting QTI to Learnosity JSON.

We have a problem where duplicate passages are being created because we create new UUID for the widget reference every time we convert QTI to JSON.

Can we look at hashing the body of the passage and use that as both the item and widget reference? This would mean that in a single QTI content package, we would re-use the same sharedpassage if it was used in multiple items. But also when separate QTI content packages were converted, we’d keep the same sharedpassage reference, and therefore actually “share” the passage, rather than creating a brand new one.

### CODE REVIEW

**Comment by michaelsharman** [comment]
@rakeshqdsa it looks like the hashed value used for the passage is not the same for the passage-only items.

The desired outcome, is that the passage reference (the hash of the contents) is the same value whether used on passage-question items, or passage-only items.

**Comment by michaelsharman** [comment]
@rakeshqdsa this seems to be creating a passage reference from a hash for passage-question items, but not for passage-only items.

The desire is that anytime a passage is created, it's done using a hash of the contents as the reference.

**Comment by rakeshqdsa** [comment]
I am not getting your point here can you please explain a title bit more with an example .

**Comment by michaelsharman** [comment]
This is working well, a slight change is to leave the item reference as it was (a UUID). Eg:
`$itemData['reference'] = UuidUtil::generate();`

**Comment by rakeshqdsa** [comment]
Done

**Pull request merged**
