### PR TITLE
Learnosity MCQ standard conversion to qti 2.1 And Generation of Manifest file and IMS content package

### PR DESCRIPTION
**Pull request by pooja31chaudhary**
This commit include conversion updates for mcq standard (single response) type question. Code for adding feedback inline updated in this commit . For processing feedback also need to do some changes in <responseProcessing> , which will be committed in next update.

### CODE REVIEW

**Comment by rakeshqdsa** [comment]
Following Task also added in the PR
ResponseProcessing updated for MCQ single response question
Generation of manifest files and IMS content package

**Comment by rakeshqdsa** [comment]
Here is the JIRA tickets 
https://learnosity.atlassian.net/browse/WBL-3
https://learnosity.atlassian.net/browse/WBL-4
https://learnosity.atlassian.net/browse/WBL-5
https://learnosity.atlassian.net/browse/WBL-6
https://learnosity.atlassian.net/browse/WBL-7
https://learnosity.atlassian.net/browse/WBL-8
https://learnosity.atlassian.net/browse/WBL-9
https://learnosity.atlassian.net/browse/WBL-10
https://learnosity.atlassian.net/browse/WBL-11
https://learnosity.atlassian.net/browse/WBL-12
https://learnosity.atlassian.net/browse/WBL-13
https://learnosity.atlassian.net/browse/WBL-14

**Comment by rakeshqdsa** [comment]
Please do not provide any feedback on this pull . We are splitting this PR in small chunks .

**Comment by ttton** [comment]
Hi @pooja31chaudhary, could you please run PHP_CodeSniffer on this branch? It might resolve quite a few of the code quality/style issues I've found in my review, and save the effort of fixing them individually for yourself.

**Comment by rakeshqdsa** [comment]
Hi,
This is very old PR and we are in the process of splitting this PR into small chunks . Whenever we create a small PR from this PR we will run the codesniffer on the smaller PR .
Will it work ?

**Comment by ttton** [comment]
> Hi,
> This is very old PR and we are in the process of splitting this PR into small chunks . Whenever we create a small PR from this PR we will run the codesniffer on the smaller PR .
> Will it work ?

Ok that's fine, can we close this PR then? I'd rather not leave PRs open if they won't be merged.

**Comment by ttton** [comment]
@rakeshqdsa I'm a bit confused about the status of this PR, I can see commits being added but I understand it's not an active PR anymore? Should there be any more code pushed to this branch?

**Comment by ttton** [comment]
I'm going to close this for now - I'm assuming that the branch is still being pushed to for development or testing purposes only, and that there does not need to be a PR associated.

**Pull request closed without merging**
